"""add ibiga food models

Revision ID: 1682535ccb73
Revises: 
Create Date: 2026-03-24 13:49:54.047984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1682535ccb73'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prospects',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('inquiry_path', sa.Enum('매장방문', '매체광고', '인터넷검색', '소개추천', '기타', name='inquirypath'), nullable=False),
    sa.Column('hope_region', sa.String(length=100), nullable=True),
    sa.Column('startup_budget', sa.Integer(), nullable=True),
    sa.Column('tasted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('신규', '진행중', '성약', '종료', name='prospectstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('승인대기', '관리자', '활성', '비활성유저', name='userstatus'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('terms_of_service', sa.Boolean(), nullable=False),
    sa.Column('privacy_policy_agreement', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('admin', 'executive', 'dev_manager', 'dev_staff', 'supervisor_manager', 'supervisor', name='userrole'), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('consultations',
    sa.Column('prospect_id', sa.String(length=36), nullable=False),
    sa.Column('consultation_order', sa.Integer(), nullable=False),
    sa.Column('consultant_id', sa.String(length=36), nullable=False),
    sa.Column('consultation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('result', sa.Enum('A가망고객', 'B지속고객', 'C종료의지없음', name='consultationresult'), nullable=False),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consultant_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jwt',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('access', sa.Text(), nullable=False),
    sa.Column('refresh', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('stores',
    sa.Column('store_name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('supervisor_id', sa.String(length=36), nullable=True),
    sa.Column('store_size', sa.Integer(), nullable=True),
    sa.Column('opening_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('운영중', '휴점', '폐점', name='storestatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supervisor_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_name')
    )
    op.create_table('store_inspections',
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('supervisor_id', sa.String(length=36), nullable=False),
    sa.Column('inspection_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quality_status', sa.Enum('준수', '미흡', name='qualitystatus'), nullable=False),
    sa.Column('quality_notes', sa.Text(), nullable=True),
    sa.Column('hygiene_status', sa.Enum('양호', '미흡', name='hygienestatus'), nullable=False),
    sa.Column('hygiene_notes', sa.Text(), nullable=True),
    sa.Column('sales_amount', sa.Integer(), nullable=True),
    sa.Column('sales_yoy_change', sa.Float(), nullable=True),
    sa.Column('sales_mom_change', sa.Float(), nullable=True),
    sa.Column('staff_count', sa.JSON(), nullable=True),
    sa.Column('market_change', sa.Text(), nullable=True),
    sa.Column('owner_feedback', sa.Text(), nullable=True),
    sa.Column('improvement_items', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('improvement_tasks',
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.Enum('품질', '위생', '매출', '인력', '상권', '기타', name='taskcategory'), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('높음', '중간', '낮음', name='taskpriority'), nullable=False),
    sa.Column('status', sa.Enum('미처리', '진행중', '완료', '보류', name='taskstatus'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['store_inspections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('improvement_tasks')
    op.drop_table('store_inspections')
    op.drop_table('stores')
    op.drop_table('jwt')
    op.drop_table('consultations')
    op.drop_table('user')
    op.drop_table('prospects')
    # ### end Alembic commands ###
